spring:
  application:
    name: logistics-service

  datasource:
    url: jdbc:mysql://10.156.0.4/spring
    username: reda
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: true

server:
  port: 8094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
